version: 2.0

jobs:
  # Base test configuration for Go library tests Each distinct version should
  # inherit this base, and override (at least) the container image used.
  "test": &test
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/torkashvand/goshortener
    environment:
      GO111MODULE: "on"
    steps: &steps
      # Our build steps: we checkout the repo, fetch our deps, lint, and finally
      # run "go test" on the package.
      - checkout
      # Logs the version in our build logs, for posterity
      - run: go version
      - run:
          name: "Fetch dependencies"
          command: >
            go mod download
      # Only run tests against the latest Go version
      - run:
          name: "Run tests"
          command: >
            if [ "${LATEST}" = true ]; then
              make test
            fi
      # build the application docker images
      - setup_remote_docker
      - run:
            name: "Build & Push Docker Images"
            command: |
                  echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                  make package
                  make tag
                  make push
  "latest":
    <<: *test
    environment:
      LATEST: true
      # Since we re-define the "environment" here, we need to add "GO111MODULE=on" back
      GO111MODULE: "on"
      GOSHORTENER_DB_DRIVER: sqlite3
      GOSHORTENER_BASE_REDIRECT_SERVER: http://127.0.0.1:8080/redirect/

  "1.14":
    # This is the neat trick: the <<: *test references the, well, &test reference
    # we created above. If we want to override any sub-object, we just need to supply
    # that object, and not copy+paste the entire object (at risk of typo, or misconfig)
    <<: *test
    docker:
      - image: circleci/golang:1.14

workflows:
  version: 2
  build:
    jobs:
      # Self-explanatory: we run all of our builds. We could potentially
      # add a "requires: latest" to the specific version tags, if we wanted to
      # attempt to build latest first (only).
      - "latest"
      - "1.14"
